{"name": "test_01", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <tjxg3_ph.TJXG3PH object at 0x7f6fac320970>\n\n    @pytest.mark.asyncio\n    @pytest.mark.run(order=1)\n    @allure.title('test_01')\n    async def test_01(self):\n        await set_ph_sp(10)\n        await set_ph_sp_source('Fixed')\n        await asyncio.sleep(2)\n        pv1 = await get_ph_pv()\n        if pv1 > 0:\n            await set_ph_sp_source('Disable')\n            await asyncio.sleep(2)\n            pv2 = await get_ph_pv()\n            if math.fabs(pv2) > 1e-10:\n                allure.attach(body=f'curr pv is {pv2}, expect is zero', name='Error', attachment_type=allure.attachment_type.TEXT)\n                assert False\n        else:\n            allure.attach(body=f'curr pv is {pv1}, expect is greater than zero', name='Error', attachment_type=allure.attachment_type.TEXT)\n>           assert False\nE           assert False\n\ntests/G3/tjxg3_ph.py:38: AssertionError"}, "attachments": [{"name": "Error", "source": "2e758235-7b89-492b-9d65-633137528014-attachment.txt", "type": "text/plain"}], "start": 1752828175166, "stop": 1752828183179, "uuid": "d00332db-9e06-4cef-b8bf-a0edfbdb2972", "historyId": "625040f8774a2a40ba3d11c3991c993a", "testCaseId": "625040f8774a2a40ba3d11c3991c993a", "fullName": "tests.G3.tjxg3_ph.TJXG3PH#test_01", "labels": [{"name": "feature", "value": "pH"}, {"name": "tag", "value": "asyncio"}, {"name": "tag", "value": "pH"}, {"name": "parentSuite", "value": "tests.G3"}, {"name": "suite", "value": "tjxg3_ph"}, {"name": "subSuite", "value": "TJXG3PH"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "152347-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.G3.tjxg3_ph"}]}