{"name": "test_02", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <tjxg3_agit.TJXG3Agit object at 0x7f8828645220>\n\n    @pytest.mark.asyncio\n    @pytest.mark.run(order=2)\n    @allure.title('test_02')\n    async def test_02(self):\n        await set_agit_sp_source('Fixed')\n        for it in get_agit_sps():\n            pv1 = await get_agit_pv()\n            await set_agit_sp(it)\n            elapsed_time, timeout = await self.pv_close_to_sp(it)\n            pv2 = await get_agit_pv()\n            if elapsed_time is not None:\n                allure.attach(body=f'{pv1}->{it} speed {elapsed_time} s, curr pv is {pv2}', name='Comment', attachment_type=allure.attachment_type.TEXT)\n            else:\n                allure.attach(body=f'{pv1}->{it} speed {timeout} s, curr pv is {pv2}', name='Error', attachment_type=allure.attachment_type.TEXT)\n                await set_agit_sp_source('Disable')\n>               assert False\nE               assert False\n\ntests/G3/tjxg3_agit.py:55: AssertionError"}, "attachments": [{"name": "Error", "source": "73776314-37fd-441e-8cf9-27f2720e7ab9-attachment.txt", "type": "text/plain"}], "start": 1752828183199, "stop": 1752828196220, "uuid": "8f35a65f-40e7-4c3f-8230-d58861914a5a", "historyId": "dbf112c01c874cd784ee1e4574432fc8", "testCaseId": "dbf112c01c874cd784ee1e4574432fc8", "fullName": "tests.G3.tjxg3_agit.TJXG3Agit#test_02", "labels": [{"name": "feature", "value": "Agit"}, {"name": "tag", "value": "asyncio"}, {"name": "tag", "value": "Agit"}, {"name": "parentSuite", "value": "tests.G3"}, {"name": "suite", "value": "tjxg3_agit"}, {"name": "subSuite", "value": "TJXG3Agit"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "152350-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.G3.tjxg3_agit"}]}