{"name": "test_02", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <tjxg3_do.TJXG3DO object at 0x7f8828645040>\n\n    @pytest.mark.asyncio\n    @pytest.mark.run(order=2)\n    @allure.title('test_02')\n    async def test_02(self):\n        await set_do_sp_source('Fixed')\n        for it in get_do_sps():\n            pv1 = await get_do_pv()\n            await set_do_sp(it)\n            elapsed_time, timeout = await self.pv_close_to_sp(it)\n            pv2 = await get_do_pv()\n            if elapsed_time is not None:\n                allure.attach(body=f'{pv1}->{it} speed {elapsed_time} s, curr pv is {pv2}', name='Comment', attachment_type=allure.attachment_type.TEXT)\n            else:\n                allure.attach(body=f'{pv1}->{it} speed {timeout} s, curr pv is {pv2}', name='Error', attachment_type=allure.attachment_type.TEXT)\n                await set_do_sp_source('Disable')\n>               assert False\nE               assert False\n\ntests/G3/tjxg3_do.py:55: AssertionError"}, "attachments": [{"name": "Error", "source": "ef5cc7ba-8073-404e-878f-0cc99e3ba167-attachment.txt", "type": "text/plain"}], "start": 1752828196227, "stop": 1752828209247, "uuid": "3a338bf0-9752-48b5-8b0a-25654692e5cb", "historyId": "9b73ef21abc14c9cd99c9cb23ad48839", "testCaseId": "9b73ef21abc14c9cd99c9cb23ad48839", "fullName": "tests.G3.tjxg3_do.TJXG3DO#test_02", "labels": [{"name": "feature", "value": "DO"}, {"name": "tag", "value": "asyncio"}, {"name": "tag", "value": "DO"}, {"name": "parentSuite", "value": "tests.G3"}, {"name": "suite", "value": "tjxg3_do"}, {"name": "subSuite", "value": "TJXG3DO"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "152350-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.G3.tjxg3_do"}]}